version: '3.8'
services:

  app:
    image: chaosrun/estonian-weather:latest
    container_name: estonian-weather
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:8080
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    networks:
      - ootnet

  db:
    image: postgres:latest
    container_name: estonian-weather-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ootnet

volumes:
  data:
    driver: local

networks:
  ootnet:
    name: estonian-weather-net
